create table stickers (
  id         bigint generated by default as identity primary key,
  slug       text not null unique,
  name       text not null,
  image_path text not null,
  rarity     text not null default 'normal',
  created_at timestamptz not null default now()
);
