create table login_bonus_events (
  id         bigint generated by default as identity primary key,
  user_id    uuid   not null references auth.users(id) on delete cascade,
  sticker_id bigint not null references stickers(id),
  granted_at timestamptz not null default now()
);
