create table exchange_requests (
  id                  bigint generated by default as identity primary key,
  requester_id        uuid   not null references auth.users(id) on delete cascade,
  receiver_id         uuid   not null references auth.users(id) on delete cascade,
  offered_sticker_id  bigint not null references stickers(id),
  receiver_sticker_id bigint references stickers(id),
  status              text   not null default 'pending',
  expires_at          timestamptz not null,
  created_at          timestamptz not null default now(),
  responded_at        timestamptz,

  constraint exchange_status_check
    check (status in ('pending', 'accepted', 'rejected', 'canceled', 'expired')),
  constraint no_self_exchange_check
    check (requester_id <> receiver_id)
);

create index exchange_requests_receiver_status_idx
  on exchange_requests (receiver_id, status, created_at desc);

create index exchange_requests_requester_status_idx
  on exchange_requests (requester_id, status, created_at desc);
